# Generated by Django 4.2.7 on 2023-12-01 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_watchlist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='id',
            new_name='listing_id',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
