# Generated by Django 4.2.7 on 2023-12-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_bid_time_comments_listing_id_comments_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listing_id',
            field=models.CharField(max_length=100),
        ),
    ]
