# Generated by Django 4.2.7 on 2023-12-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist_id_alter_watchlist_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='is_active',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
