# Generated by Django 4.2.7 on 2023-12-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='is_active',
            field=models.BooleanField(default=True, max_length=10),
        ),
    ]
