# Generated by Django 4.2.7 on 2023-12-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_comments_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listing_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
