# Generated by Django 5.0.1 on 2024-04-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_watchlist_id_alter_watchlist_listing_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='listings',
            new_name='Listing',
        ),
    ]
