# Generated by Django 5.0.1 on 2024-04-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_comments_comment_rename_listings_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listing_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='listing_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listing_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
